USE SuperHeroesDB;

CREATE TABLE Superhero(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Alias NVARCHAR(50) NOT NULL,
	Origin NVARCHAR(50)
);

CREATE TABLE Assistant(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Power(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(500)
);